header:
  - name: Home
    pageRef: /
    weight: 1
  - name: Case studies
    pageRef: /case-studies
    weight: 2
  - name: Impact
    pageRef: /impact
    weight: 3
  - name: Datasets
    pageRef: /datasets
    weight: 4
  - name: About
    pageRef: /about
    weight: 5
footer:
  - name: Privacy policy
    pageRef: /privacy-policy
    weight: 1
  - name: Legal notice
    pageRef: /legal-notice
    weight: 2
  - name: "Accessibility: not compliant"
    pageRef: /accessibility
    weight: 3
  - name: Media
    pageRef: /media
    weight: 4
