header:
  - name: Memos
    pageRef: /memos
    weight: 1
  - name: Datasets
    pageRef: /datasets
    weight: 2
  - name: Documentation
    url: https://docs.opentermsarchive.org
    weight: 3
  - name: Impact
    pageRef: /impact
    weight: 3
  - name: About
    pageRef: /about
    weight: 5
footer:
  - name: Home
    pageRef: /
    weight: 1
  - name: Memos
    pageRef: /memos
    weight: 2
  - name: Datasets
    pageRef: /datasets
    weight: 3
  - name: Documentation
    pageRef: /
    weight: 4
  - name: Impact
    pageRef: /impact
    weight: 5
  - name: About
    pageRef: /about
    weight: 6
first_subfooter:
  - name: Statistics
    pageRef: /stats
    weight: 1
  - name: Media
    pageRef: /media
    weight: 2
  - name: Source code
    url: https://github.com/ambanum/OpenTermsArchive
    weight: 3
second_subfooter:
  - name: Legal notice
    pageRef: /legal-notice
    weight: 1
  - name: Privacy policy
    pageRef: /privacy-policy
    weight: 2
  - name: 'Accessibility: not compliant'
    pageRef: /accessibility
    weight: 3
