mounts:
  - source: data/collections.json
    target: static/collections.json
  - source: assets/images/
    target: static/images/
  - source: assets
    target: assets
  - source: .all-contributorsrc
    target: assets/allcontributorsrc.json
  - source: node_modules/minireset.css/minireset.css
    target: assets/css/vendor/minireset.css
