contact_email: contact@opentermsarchive.org
mastodon: 
  url: https://mastodon.lescommuns.org/@opentermsarchive
  username: "@opentermsarchive@mastodon.lescommuns.org"
twitter: 
  url: https://twitter.com/OpenTerms
github:
  url: https://github.com/OpenTermsArchive
contributors:
  local: allcontributorsrc.json
  remote:
    - https://raw.githubusercontent.com/OpenTermsArchive/engine/main/.all-contributorsrc
