extends:
  - "plugin:@html-eslint/recommended"
plugins: 
  - "@html-eslint"
parser: "@html-eslint/parser"
rules:
  "@html-eslint/require-img-alt": warn
  "@html-eslint/indent": off
  "@html-eslint/element-newline":
    - error
    - skip:
      - pre
      - code
  "@html-eslint/no-duplicate-attrs": warn
