'files':
  [
    {
      'source': '/public/locales/en/*.json',
      'translation': /public/locales/%two_letters_code%/%original_file_name%,
    },
    {
      'source': '/src/pages/**/*.en.mdx',
      'translation': '/src/pages/**/%file_name%.%two_letters_code%.mdx',
      'translation_replace': { '.en': '' },
    },
  ]
