all:
  children:
    dev:
      hosts:
        51.75.169.235:
          ansible_user: debian
          ansible_ssh_extra_args: -o StrictHostKeyChecking=no
          ansible_python_interpreter: /usr/bin/python3 # Needed or it fails with 'Failed to import the required Python library'
