name: Test

on:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - name: Lint Markdown
        run: npm run lint:markdown
      - name: Lint CSS
        run: npm run lint:css
      - name: Lint JavaScript
        run: npm run lint:js
      - name: Lint HTML
        run: npm run lint:html
      - name: Set Hugo up
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.122.0'
          extended: true
      - name: Test broken links
        run: npm run test:links -- --skip '^(?!https?://(www.opentermsarchive.org|netlify.app))'
      - name: Validate HTML
        run: npm run test:html
      - name: Test i18n
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:1313'
          config-file: test/cypress/cypress.config.js
          spec: |
            test/cypress/e2e/contributors.cy.js
            test/cypress/e2e/i18n.cy.js
